grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - bsdev.grafana.com
    tls:
      - secretName: monitoring-tls
        hosts:
          - bsdev.grafana.com
  persistence:
    enabled: true
    size: 5Gi

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

prometheus-node-exporter:
  enabled: true

kube-state-metrics:
  enabled: true
