alertmanager:
  persistentVolume:
    enabled: true
    storageClass: "standard"
    size: 2Gi

server:
  persistentVolume:
    enabled: true
    storageClass: "standard"
    size: 8Gi

  service:
    type: NodePort
    nodePort: 30090  # Prometheus Web UI 접근 포트

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

