apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: valheim-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.30.1.150-172.30.1.160
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: valheim-adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - valheim-ip-pool

