grafana:
  enabled: false
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10G
          volumeName: prometheus-pv
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      runAsNonRoot: false
